name: CI-Object-Storage-Yandex-Cloud

# on:
# #  push:
# #    branches: [ main ]
#   pull_request:
#     branches: [ "main" ]
# name: Release

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:    
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'giftstat-doc'
        AWS_ACCESS_KEY_ID: ${{ secrets.DIPLODOC_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DIPLODOC_SECRET_ACCESS_KEY }}
        AWS_S3_ENDPOINT: 'https://storage.yandexcloud.net'
        # AWS_REGION: 'us-west-1'   # optional: defaults to us-east-1
        SOURCE_DIR: "./docs"      # optional: defaults to entire repository
